# -*- coding: utf-8 -*-
"""app_xG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155aDzN1xZLSOGu_wgLtDzAxF9Daup2dK
"""


import streamlit as st
import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor

# Cargar modelo y encoder
modelo = joblib.load("modelo_prueba.pkl")
encoder = joblib.load("encoder_ohe.pkl")

st.title("Calculadora de xG")

# Coordenadas
st.subheader("Coordenadas del disparo")
x = st.slider("Eje X (largo del campo)", 0, 120, 100)
y = st.slider("Eje Y (ancho del campo)", 0, 80, 40)

# Características del disparo
body_part = st.selectbox("Parte del cuerpo", ["Right Foot", "Left Foot", "Head"])
shot_technique = st.selectbox("Técnica", ["Normal", "Volley", "Lob"])
shot_type = st.selectbox("Tipo", ["Open Play", "Free Kick", "From Corner"])
play_pattern = st.selectbox("Patrón de juego", ["Regular Play", "From Counter", "From Throw In"])
under_pressure = st.checkbox("Bajo presión")
one_on_one = st.checkbox("Uno contra uno")
open_goal = st.checkbox("Portería vacía")
aerial_won = st.checkbox("Remate aéreo ganado")
first_time = st.checkbox("Disparo de primeras")
deflected = st.checkbox("Desviado")

# Cálculo distancia y ángulo
goal_x, goal_y = 120, 40
distance = np.sqrt((goal_x - x)**2 + (goal_y - y)**2)

def calcular_angulo(x, y):
    left_post = np.array([120, 34])
    right_post = np.array([120, 46])
    shot_point = np.array([x, y])
    v1 = left_post - shot_point
    v2 = right_post - shot_point
    cos_angle = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    angle_rad = np.arccos(np.clip(cos_angle, -1.0, 1.0))
    return np.degrees(angle_rad)

angle = calcular_angulo(x, y)

# Preparar input
input_df = pd.DataFrame([{
    'shot_body_part': body_part,
    'play_pattern': play_pattern,
    'under_pressure': str(under_pressure),
    'shot_one_on_one': str(one_on_one),
    'shot_open_goal': str(open_goal),
    'shot_aerial_won': str(aerial_won),
    'shot_first_time': str(first_time),
    'shot_deflected': str(deflected),
    'shot_technique': shot_technique,
    'shot_type': shot_type
}])

X_cat = encoder.transform(input_df)
X_cat_df = pd.DataFrame(X_cat, columns=encoder.get_feature_names_out(), index=input_df.index)
X_num = pd.DataFrame([[distance, angle]], columns=["distance", "angle"])
X_final = pd.concat([X_num, X_cat_df], axis=1)

expected_features = modelo.get_booster().feature_names
for col in expected_features:
    if col not in X_final.columns:
        X_final[col] = 0.0
X_final = X_final[expected_features]

# Predecir
pred_xg = modelo.predict(X_final)[0]
st.success(f"xG estimado: **{pred_xg:.3f}**")
